language: php
php:
 - 7.3.5

services:
  - postgresql

before_script:
  - psql -c "CREATE USER slamquiz WITH PASSWORD 'db_password';" -U postgres
  - psql -c "CREATE DATABASE slamquiz;" -U postgres
  - psql -c "GRANT ALL PRIVILEGES ON DATABASE slamquiz TO slamquiz;" -U postgres

env:
    - DATABASE_URL="pgsql://slamquiz:db_password@127.0.0.1:5432/slamquiz"

script:
 - composer install
 - php bin/console doctrine:migrations:migrate -n
 - php bin/console doctrine:fixtures:load -q
 - php bin/phpunit